backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  #identity_url: "https://www.la-petite-bete-qui-pique.fr/.netlify/identity"
  #gateway_url: "https://www.la-petite-bete-qui-pique.fr/.netlify/git"
  #login: true
  #roles: ["admin", "editor"]

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }